### ISSUE TITLE
Error occurred trying to load an EventBusSubscriber

### ISSUE THREAD

**Issue by Trifectus** [GreatOrator/TolkienTweaks-Mobs#18]
I encountered the error first here: https://pastebin.com/jptCnMtC

and after some messing about with my server and tweaking some other things I've readded Tolkien Tweaks - Mobs to see if it had fixed itself but it didn't, below is the updated crash report for comparison.

## Base information
* Minecraft version: 1.12.2
* Minecraft Forge version: forge-1.12.2-14.23.5.2838-universal
* TolkienTweaks-Mobs version: TolkienMobs-1.12.2-1.12.20.13.0-universal

## Crash report
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (spongeforge-1.12.2-2838-7.1.7-RC3862.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 7/29/19 10:03 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityPlayerSP
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:89)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:612)
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.redirect$forgeImpl$PostEvent$zza000(LoadController.java:568)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityPlayerSP
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
	at java.lang.Class.privateGetPublicMethods(Unknown Source)
	at java.lang.Class.getMethods(Unknown Source)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:82)
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:82)
	... 32 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.entity.EntityPlayerSP
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 38 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@43effd89 from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 40 more
Caused by: java.lang.RuntimeException: Attempted to load class bud for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
	... 42 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:89)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:612)
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.redirect$forgeImpl$PostEvent$zza000(LoadController.java:568)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)

-- Sponge PhaseTracker --
Details:
	Phase Stack: [Empty stack]
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjb000(MinecraftServer.java:4720)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:889)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:371)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:558)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 702575752 bytes (670 MB) / 2028994560 bytes (1935 MB) up to 5719457792 bytes (5454 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 48 mods loaded, 48 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	Mods:

	| State | ID                  | Version                  | Source                                            | Signature                                |
	|:----- |:------------------- |:------------------------ |:------------------------------------------------- |:---------------------------------------- |
	| LC    | minecraft           | 1.12.2                   | minecraft.jar                                     | None                                     |
	| LC    | mcp                 | 9.42                     | minecraft.jar                                     | None                                     |
	| LC    | FML                 | 8.0.99.99                | forge-1.12.2-14.23.5.2838-universal.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge               | 14.23.5.2838             | forge-1.12.2-14.23.5.2838-universal.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | spongeapi           | 7.1.0-c23f58d2a          | spongeforge-1.12.2-2838-7.1.7-RC3862.jar          | None                                     |
	| LC    | sponge              | 1.12.2-7.1.7-SNAPSHOT    | spongeforge-1.12.2-2838-7.1.7-RC3862.jar          | None                                     |
	| LC    | spongeforge         | 1.12.2-2838-7.1.7-RC3862 | spongeforge-1.12.2-2838-7.1.7-RC3862.jar          | None                                     |
	| LC    | baubles             | 1.5.2                    | Baubles-1.12-1.5.2.jar                            | None                                     |
	| LC    | betterbuilderswands | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar   | None                                     |
	| LC    | betterquesting      | 3.5.300                  | BetterQuesting-3.5.300.jar                        | None                                     |
	| LC    | codechickenlib      | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | redstoneflux        | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar           | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | brandonscore        | 2.4.17                   | BrandonsCore-1.12.2-2.4.17.208-universal.jar      | None                                     |
	| LC    | chisel              | MC1.12.2-0.2.1.35        | Chisel-MC1.12.2-0.2.1.35.jar                      | None                                     |
	| LC    | chiselsandbits      | 14.33                    | chiselsandbits-14.33.jar                          | None                                     |
	| LC    | customnpcs          | 1.12                     | CustomNPCs_1.12.2(30Jan19).jar                    | None                                     |
	| LC    | props               | 2.6.2                    | Decocraft-2.6.2_1.12.2.jar                        | None                                     |
	| LC    | dungeontactics      | DT-0.16.5                | DungeonTactics-1.12.2-0.16.5.jar                  | None                                     |
	| LC    | elevatorid          | 1.3.10                   | ElevatorMod-1.12.2-1.3.10.jar                     | None                                     |
	| LC    | erebus              | 1.0.30                   | Erebus-1.0.30.jar                                 | None                                     |
	| LC    | helpfixer           | 1.12.1-1.5.18            | HelpFixer-1.12.1-1.5.18.jar                       | None                                     |
	| LC    | waila               | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                       | None                                     |
	| LC    | jei                 | 4.15.0.268               | jei_1.12.2-4.15.0.268.jar                         | None                                     |
	| LC    | journeymap          | 1.12.2-5.5.4             | journeymap-1.12.2-5.5.4.jar                       | None                                     |
	| LC    | mantle              | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                          | None                                     |
	| LC    | natura              | 1.12.2-4.3.2.69          | natura-1.12.2-4.3.2.69.jar                        | None                                     |
	| LC    | twilightforest      | 3.8.689                  | twilightforest-1.12.2-3.8.689-universal.jar       | None                                     |
	| LC    | tconstruct          | 1.12.2-2.12.0.157        | TConstruct-1.12.2-2.12.0.157.jar                  | None                                     |
	| LC    | plustic             | 7.0.7.0                  | plustic-7.0.7.0.jar                               | None                                     |
	| LC    | tinkertoolleveling  | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar               | None                                     |
	| LC    | tolkientweaks       | 3.0.7.6                  | TolkienTweaks-1.12.2-3.0.7.6.38-universal.jar     | None                                     |
	| LE    | tolkienmobs         | 1.12.20.13               | TolkienMobs-1.12.2-1.12.20.13.0-universal.jar     | None                                     |
	| L     | worldedit           | 6.1.10-SNAPSHOT          | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar | None                                     |


	Plugins:

	| State | ID               | Version     | Source                                  | Signature |
	|:----- |:---------------- |:----------- |:--------------------------------------- |:--------- |
	| LC    | catclearlag      | 0.9.0       | CatClearLag-0.9.0.jar                   | None      |
	| LC    | chestrefill      | 1.4.0       | ChestRefill-1.12.2-1.4.0.jar            | None      |
	| LC    | handytorch       | 1.0.0       | HandyTorch-1.0.0.jar                    | None      |
	| LC    | hdb              | 1.0.4       | headdatabase-1.0-SNAPSHOT.jar           | None      |
	| LC    | langswitch       | 1.4         | LangSwitch-1.4.jar                      | None      |
	| LC    | luckperms        | 4.3.75      | LuckPerms-Sponge-4.3.75.jar             | None      |
	| LC    | megamenus        | 0.5         | Mega Menus-0.5.jar                      | None      |
	| LC    | dosmike_toolbbox | 1.1.1       | Mike's ToolBox-1.1.1.jar                | None      |
	| LC    | nucleus          | 1.13.0-S7.1 | Nucleus-1.13.0-S7.1-MC1.12.2-plugin.jar | None      |
	| LC    | petblocks        | 8.6.0       | PetBlocks-Sponge.jar                    | None      |
	| LC    | pjc              | 0.3.0       | projectcore-7.2.0-0.3.0.jar             | None      |
	| LC    | titlezones       | 1.1.0       | Title Zones-1.1.0-SpongeAPI-7.jar       | None      |
	| L     | totaleconomy     | 1.8.1       | TotalEconomy-1.8.1.jar                  | None      |
	| L     | vshop            | 2.1.0       | VillagerShops-2.1.0.jar                 | None      |
	| L     | warpspawns       | 1.0.2       | WarpSpawns-1.0.2.jar                    | None      |

	Loaded coremods (and transformers): 
SpongeCoremod (spongeforge-1.12.2-2838-7.1.7-RC3862.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)


```

**Comment by GreatOrator** [comment]
After a lot of testing I have still been unable to replicate this.  My code does not even use the class mentioned in the error at all which leads me to believe that another mod is modifying base code that is somehow accessed by another method I use but can't track it down.

Have you tried eliminating other mods until the crash goers away to see who may be the cause? (the crash is not because of my mod per se, but some change another mod makes but is manifested by my mod for some unknown reason.

**Comment by GreatOrator** [comment]
Ok, so found what was causing it, sorry it took so long.  Update was pushed to curse and should be available shortly.

https://github.com/GreatOrator/TolkienTweaks-Mobs/commit/dcb2855dd2964bc458a0dbd8b14807b53c733c41
