### ISSUE TITLE
Crash when trying to launch the game without JEI

### ISSUE THREAD

**Issue by K1ntus** [GreatOrator/TolkienTweaks-Mobs#19]
## Description

Game crash during the mod loading. Only client side

## Base information
* Minecraft version: 1.12.2
* Minecraft Forge version: latest stable (something like 2838)
* TolkienTweaks-Mobs version: TolkienMobs-1.12.2-1.12.24.36.0-universal

## Crash report
```

java.lang.NoClassDefFoundError: mezz/jei/util/Translator
	at com.greatorator.tolkienmobs.handler.TTMLore.func_77624_a(TTMLore.java:34)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:707)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:576)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:590)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:529)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: mezz.jei.util.Translator
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 16 more
Caused by: java.lang.NullPointerException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.greatorator.tolkienmobs.handler.TTMLore.func_77624_a(TTMLore.java:34)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:707)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:576)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:590)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:529)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

```

**Comment by GreatOrator** [comment]
Yeah, was reported to me about....2 hoursago in my discord.  Already looking in to it.  Should not be a requirement

**Comment by GreatOrator** [comment]
Latest push should fix this, uploaded to curse.

**Comment by K1ntus** [comment]
Sorry, I'm currently not using your discord. Thanks for fixing it that fast anyways ;)

**Comment by GreatOrator** [comment]
Not a problem, was more to let you know I was on it already :D

Glad it is working fine for you now :D
