### ISSUE TITLE
Crash after enchanting mithril boots

### ISSUE THREAD

**Issue by celittle3** [GreatOrator/TolkienTweaks-Mobs#21]
## Base information
* Minecraft version: 1.12.2
* Minecraft Forge version: 1.12.2-forge1.12.2-14.23.5.2847
* TolkienTweaks-Mobs version: TolkienMobs-1.12.2-1.12.30.37.0-universal

## Crash report
```
java.lang.IllegalArgumentException: Invalid operation
	at org.apache.commons.lang3.Validate.inclusiveBetween(Validate.java:1055)
	at net.minecraft.entity.ai.attributes.AttributeModifier.<init>(SourceFile:32)
	at com.greatorator.tolkienmobs.handler.TTMEnchantHandler.AddResolve(TTMEnchantHandler.java:96)
	at com.greatorator.tolkienmobs.handler.TTMEnchantHandler.gondorianResolve(TTMEnchantHandler.java:82)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1937_TTMEnchantHandler_gondorianResolve_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:581)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2095)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.apache.commons.lang3.Validate.inclusiveBetween(Validate.java:1055)
	at net.minecraft.entity.ai.attributes.AttributeModifier.<init>(SourceFile:32)
	at com.greatorator.tolkienmobs.handler.TTMEnchantHandler.AddResolve(TTMEnchantHandler.java:96)
	at com.greatorator.tolkienmobs.handler.TTMEnchantHandler.gondorianResolve(TTMEnchantHandler.java:82)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1937_TTMEnchantHandler_gondorianResolve_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:581)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2095)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 107
	Entity Name: Wreckage
	Entity's Exact location: 2826.79, 64.00, 313.33
	Entity's Block location: World: (2826,64,313), Chunk: (at 10,4,9 in 176,19; contains blocks 2816,0,304 to 2831,255,319), Region: (5,0; contains chunks 160,0 to 191,31, blocks 2560,0,0 to 3071,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@6105b1c1
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2450170856 bytes (2336 MB) / 6947397632 bytes (6625 MB) up to 12871532544 bytes (12275 MB)
	JVM Flags: 6 total; -Xmx12G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 266 mods loaded, 266 mods active
```

**Comment by GreatOrator** [comment]
Should be fixed with commit https://github.com/GreatOrator/TolkienTweaks-Mobs/commit/d934ad7931e50532e74c74f8262786c2fd826fce

Will be packaging and updating curseforge with new version shortly
