### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Spyeegle** [GreatOrator/TolkienTweaks-Mobs#24]
## Description
The game crashes on startup using Tolkien tweaks mob edition. (the final goal is to use it with a free Aternos server to get Lotr mobs)

## Base information
* Minecraft version:    1.16.5
* Minecraft Forge version:    forge-1.16.5-36.2.20
* TolkienTweaks-Mobs version:    1.16.5-2.0.0-beta.1-universal

## Crash report
```
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 21/01/22 15:43
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$9178/2009593531.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(Util.java:430) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$8419/1227593995.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:172) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:802) [?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.20.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$475/1886301021.call(Unknown Source) [forge-1.16.5-36.2.20.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.lang.Class.getDeclaredMethod(Class.java:2130) ~[?:1.8.0_51] {}
-- MOD tolkienmobs --
Details:
	Caused by 0: java.lang.ExceptionInInitializerError
		at com.greatorator.tolkienmobs.proxy.ClientProxy.commonSetup(ClientProxy.java:59) ~[?:1.16.5-2.0.0-alpha.1] {re:classloading}
		at com.greatorator.tolkienmobs.TolkienMobs.onCommonSetup(TolkienMobs.java:111) ~[?:1.16.5-2.0.0-alpha.1] {re:classloading}
		at net.minecraftforge.eventbus.ASMEventHandler_493_TolkienMobs_onCommonSetup_FMLCommonSetupEvent.invoke(.dynamic) ~[?:?] {}
		at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.eventbus.EventBus$$Lambda$3188/1601055449.invoke(Unknown Source) ~[?:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:36.2] {re:classloading}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.ModContainer$$Lambda$3247/634435864.run(Unknown Source) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

	Caused by 1: net.minecraftforge.fml.common.ObfuscationReflectionHelper$UnableToFindMethodException: java.lang.NoSuchMethodException: net.minecraft.village.PointOfInterestType.registerBlockStates(net.minecraft.village.PointOfInterestType)
		at net.minecraftforge.fml.common.ObfuscationReflectionHelper.findMethod(ObfuscationReflectionHelper.java:166) ~[?:?] {re:classloading}
		at com.greatorator.tolkienmobs.entity.merchant.villager.VillagerTTMUtility.<clinit>(VillagerTTMUtility.java:23) ~[?:1.16.5-2.0.0-alpha.1] {re:classloading}
		at com.greatorator.tolkienmobs.proxy.ClientProxy.commonSetup(ClientProxy.java:59) ~[?:1.16.5-2.0.0-alpha.1] {re:classloading}
		at com.greatorator.tolkienmobs.TolkienMobs.onCommonSetup(TolkienMobs.java:111) ~[?:1.16.5-2.0.0-alpha.1] {re:classloading}
		at net.minecraftforge.eventbus.ASMEventHandler_493_TolkienMobs_onCommonSetup_FMLCommonSetupEvent.invoke(.dynamic) ~[?:?] {}
		at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.eventbus.EventBus$$Lambda$3188/1601055449.invoke(Unknown Source) ~[?:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:36.2] {re:classloading}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.ModContainer$$Lambda$3247/634435864.run(Unknown Source) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

	Mod File: TolkienMobs-1.16.5-2.0.0-beta.1-universal.jar
	Failure message: Tolkien Tweaks (Mobs Edition) (tolkienmobs) encountered an error during the common_setup event phase
		java.lang.ExceptionInInitializerError: null
	Mod Version: 2.0.0-alpha.1
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.NoSuchMethodException: net.minecraft.village.PointOfInterestType.registerBlockStates(net.minecraft.village.PointOfInterestType)
Stacktrace:
	at java.lang.Class.getDeclaredMethod(Class.java:2130) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.common.ObfuscationReflectionHelper.findMethod(ObfuscationReflectionHelper.java:160) ~[?:?] {re:classloading}
	at com.greatorator.tolkienmobs.entity.merchant.villager.VillagerTTMUtility.<clinit>(VillagerTTMUtility.java:23) ~[?:1.16.5-2.0.0-alpha.1] {re:classloading}
	at com.greatorator.tolkienmobs.proxy.ClientProxy.commonSetup(ClientProxy.java:59) ~[?:1.16.5-2.0.0-alpha.1] {re:classloading}
	at com.greatorator.tolkienmobs.TolkienMobs.onCommonSetup(TolkienMobs.java:111) ~[?:1.16.5-2.0.0-alpha.1] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_493_TolkienMobs_onCommonSetup_FMLCommonSetupEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3188/1601055449.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:36.2] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3247/634435864.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4402181472 bytes (4198 MB) / 5905580032 bytes (5632 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 12
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.20.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.20.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.20.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.20.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G8.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.20.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.20
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.20-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |SIDED_SETU|Manifest: NOSIGNATURE
		StructuresPlusEnd.jar                             |Structure plus ii             |structure_plus_ii             |1.0.0               |SIDED_SETU|Manifest: NOSIGNATURE
		BiomesOPlenty-1.16.5-13.1.0.485-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.5-13.1.0.485   |SIDED_SETU|Manifest: NOSIGNATURE
		abnormals_core-1.16.5-3.3.0.jar                   |Abnormals Core                |abnormals_core                |3.3.0               |SIDED_SETU|Manifest: NOSIGNATURE
		mostructures-forge-1.2.0-1.16.5.jar               |Mo' Structures                |mostructures                  |1.2.0-1.16.5        |SIDED_SETU|Manifest: NOSIGNATURE
		whisperwoods-1.16.5-2.0.2.jar                     |Whisperwoods                  |whisperwoods                  |2.0.2               |SIDED_SETU|Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.0.8.0.jar                   |Curios API                    |curios                        |1.16.5-4.0.8.0      |SIDED_SETU|Manifest: NOSIGNATURE
		LurkerMod(FORGE-1.16.4)+-+1.0.8.jar               |Lurker                        |lurkermod                     |1.16.4-1.0.8        |SIDED_SETU|Manifest: NOSIGNATURE
		journeymap-1.16.5-5.8.0beta10.jar                 |Journeymap                    |journeymap                    |5.8.0beta10         |SIDED_SETU|Manifest: NOSIGNATURE
		citadel-1.8.1-1.16.5.jar                          |Citadel                       |citadel                       |1.8.1               |SIDED_SETU|Manifest: NOSIGNATURE
		alexsmobs-1.12.0.jar                              |Alex's Mobs                   |alexsmobs                     |1.12.0              |SIDED_SETU|Manifest: NOSIGNATURE
		AdventuresStructures_3.3.1.jar                    |StructuresAdventures          |structuresadventures          |3.3.1               |SIDED_SETU|Manifest: NOSIGNATURE
		betteranimalsplus-1.16.5-11.0.3-forge.jar         |Better Animals Plus           |betteranimalsplus             |1.16.5-11.0.3       |SIDED_SETU|Manifest: NOSIGNATURE
		architectury-1.28.48.jar                          |Architectury                  |architectury                  |1.28.48             |SIDED_SETU|Manifest: NOSIGNATURE
		iceandfire-2.1.9-1.16.5.jar                       |Ice and Fire                  |iceandfire                    |2.1.9-1.16.5        |SIDED_SETU|Manifest: NOSIGNATURE
		byg-1.3.5.jar                                     |Oh The Biomes You'll Go       |byg                           |1.3.4               |SIDED_SETU|Manifest: NOSIGNATURE
		smallships-1.16.5-1.10.1.jar                      |Small Ships Mod               |smallships                    |1.10.1              |SIDED_SETU|Manifest: NOSIGNATURE
		forge-1.16.5-36.2.20-universal.jar                |Forge                         |forge                         |36.2.20             |SIDED_SETU|Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Aquaculture-1.16.5-2.1.21.jar                     |Aquaculture 2                 |aquaculture                   |1.16.5-2.1.21       |SIDED_SETU|Manifest: NOSIGNATURE
		CodeChickenLib-1.16.5-4.0.6.443-universal.jar     |CodeChicken Lib               |codechickenlib                |4.0.6.443           |SIDED_SETU|Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		TolkienMobs-1.16.5-2.0.0-beta.1-universal.jar     |Tolkien Tweaks (Mobs Edition) |tolkienmobs                   |2.0.0-alpha.1       |ERROR     |Manifest: NOSIGNATURE
		valhelsia_core-16.0.15.jar                        |Valhelsia Core                |valhelsia_core                |16.0.15             |SIDED_SETU|Manifest: NOSIGNATURE
		valhelsia_structures-1.16.5-0.1.6.jar             |Valhelsia Structures          |valhelsia_structures          |1.16.5-0.1.6        |SIDED_SETU|Manifest: NOSIGNATURE
		twilightforest-1.16.5-4.0.870-universal.jar       |The Twilight Forest           |twilightforest                |NONE                |SIDED_SETU|Manifest: NOSIGNATURE
		geckolib-forge-1.16.5-3.0.61.jar                  |GeckoLib                      |geckolib3                     |3.0.61              |SIDED_SETU|Manifest: NOSIGNATURE
		RigoranthusEmortisReborn-1.16.5-2.0.0.jar         | Rigoranthus Emortis Reborn   |rigoranthusemortisreborn      |2.0.0               |SIDED_SETU|Manifest: NOSIGNATURE
		BrandonsCore-1.16.5-3.0.11.238-universal.jar      |Brandon's Core                |brandonscore                  |3.0.11.238          |SIDED_SETU|Manifest: 53:bb:a0:11:bd:61:e2:1a:e2:cb:fd:f8:4f:e4:cd:a5:cc:12:f4:43:f0:78:68:3b:e1:62:c6:78:3b:27:ff:fe
		DynamicSurroundings-1.16.5-4.0.5.0.jar            |§3Dynamic Surroundings        |dsurround                     |4.0.5.0             |SIDED_SETU|Manifest: NOSIGNATURE
		corpse-1.16.5-1.0.6.jar                           |Corpse                        |corpse                        |1.16.5-1.0.6        |SIDED_SETU|Manifest: NOSIGNATURE
	Crash Report UUID: c6dd73a5-8b5c-4c0d-9c83-5f611d689dc6
	OptiFine Version: OptiFine_1.16.5_HD_U_G8
	OptiFine Build: 20210515-161946
	Render Distance Chunks: 10
	Mipmaps: 3
	Anisotropic Filtering: 8
	Antialiasing: 0
	Multitexture: true
	Shaders: Chocapic13_V9_High.zip
	OpenGlVersion: 4.6.0 NVIDIA 496.49
	OpenGlRenderer: NVIDIA GeForce RTX 2070/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

```

**Comment by GreatOrator** [comment]
found th4e cause of the crash and it is fixed, will be releasing an update this week with the fix
